### ISSUE TITLE
[osx] Slow opening database, search

### ISSUE THREAD

**Issue by Unixware** [zdia/gorilla#139]
In comparison to other app (PasswordSafeSWT) the Gorilla needs about 8-9sec to open my database (1sec on the PSSWT). Also searching takes some time too. While opening/searching the mouse cursor is spinning. I tried both v 13572, 13573, MacOSX 10.10.1

**Comment by zdia** [comment]
Did you read these lines on https://github.com/zdia/gorilla/wiki?

> 2014-10-27

>New MacOS bundle available at http://gorilla.dp100.com/downloads/ to fix Issue #122.

>Direct download link: http://gorilla.dp100.com/downloads/gorilla.mac.15373.zip
GPG signature: http://gorilla.dp100.com/downloads/gorilla.mac.15373.zip.sig

>If you are a MacOS user, and you receive an error message that “Gorilla is damaged”, please see the MacOS Gatekeeper Information page for details of how to allow Password Gorilla to run on your Mac.

**Comment by Unixware** [comment]
yes, I read them. My issue is slow processing of the database, maybe is by design on this app, as , to mention again, other PWsafe apps load/process my database fairly quick.

**Comment by rich123** [comment]
What is shown on the "About" (accessible via Help->About on Linux, should be via. a similar menu on Mac) just below the bullet points of Contributors and above the "License" and "Close" buttons?

If the words: "Using C sha256 extension" appear, then this is good.  It means that the compiled C extension for the SHA256 hash is working on your OS.  Zbignew is working on a compiled C extension for the encryption routine (Twofish) used by PWGorilla as well, but that code has not landed in an official release bundle yet.  It may be in a test branch, I'll let Zbignew indicate which test branch.

At present PWGorilla uses interpreted Tcl code to perform the Twofish encryption routine.  This has the advantage that the identical code operates on all OS platforms that PWGorilla supports, but has the disadvantage that it is slower than compiled C (or C++) code.

The compiled C extensions (which are themselves specific to an OS platform, so one per OS is needed) provide for performance increases compared to the interpreted Tcl code.

Since the compiled Twofish extension has not yet been made part of a release, you would need to try a source version from Github to determine if it works yet for MacOS and how much of a performance increase occurs.  But the C extension for Twofish should place PWGorilla within a very similar performance time-frame compared to other PasswordSafe apps (like PasswordSafeSWT) which are themselves compiled C or ObjectiveC.

**Comment by Unixware** [comment]
yes, the "Using C sha256 extension" is visible. I will try a version from github.

**Comment by rich123** [comment]
The C extensions appear to be on the pre-160 branch (sha:dfc68e29b151a7a98f25287e9c844edb64f6dc7b).  Use the "Download Zip" button on the bottom right of the main Github page for the tip of the branch, then unpack the .zip file and run the "gorilla.tcl" inside the sources/ folder inside.

**Comment by Unixware** [comment]
thank you, I d/l the master instead of the pre-160, well, my database loads almost instantly on the pre-160 ! The searching is a bit slow, but opening the data is improved, I will keep an eye for the next version then!
