### ISSUE TITLE
Features Request: Make browser exe path in relative

### ISSUE THREAD

**Issue by blade3** [zdia/gorilla#145]
Hi,

It whould be great if the browser executable path could be works with ./../somthings/browser.exe

For now.. when I try to use a relative path, I have a system error: no such files

Thank you!

**Comment by rich123** [comment]
There is nothing to change.  Relative paths already work, but they are, well "relative".  What they are relative to the current working directory from where you start Gorilla.  As long as the relative path finds a file at the destination, relative to Gorilla's starting directory, everything should work just fine.

But, because relative paths are relative, you have to be careful to craft them relative to the correct starting directory of your running Gorilla.

Which is why absolute paths are easier in this context, they do not depend upon the directory from where you start Gorilla.  But all Gorilla does is pass what you give it off to the operating system to launch the desired item.  Any "no such files" error you get back is your OS telling Gorilla that the relative path is not actually referencing what it should have referenced.
