### ISSUE TITLE
Auto-Save on should mark DB as saved for exit prompting

### ISSUE THREAD

**Issue by rich123** [zdia/gorilla#150]
Added on behalf of @mithrades 

If I have selected in (Preferences) the "Auto-save database immediately when changed" (box) why do I need to see the warning message when closing PG telling me the database has been modified and asking if I want to save it. Now here's the odd thing, if I click on the YES button it runs the saving progress bar again but does not shut down. If I again go to file and exit or Ctrl-X the warning box is brought up again in a 'loop.' If I then hit the NO box meaning I do not want to save the changes to the database then PG exits normally whilst still saving the changes. It took me some anxious moments to figure this out thinking I was saving then dumping my changes to close the program.

I'm suggesting if the box to save immediately in preferences is checked, the database warning box on closing PG should not have to come up. Only if that box in preferences isn't checked would the warning be required for a yes or no to save the changes, at the close of PG.

Since I can see the saving bar graph saving each change as it occurs, I feel confident on closing PG with no other reminders.

**Comment by rich123** [comment]
So far, I have been unable to recreate this effect above locally.

Are you seeing this effect with the new pre160 branch that you downloaded?

Can you list the various preference settings you have turned on/off that effect saving: auto save on change (on, obviously) but also the "backup database on save", "use save version 3 format", "time stamp backup" and "v2 unicode" settings.

As well, can you detail the exact steps you take that create the issue (i.e., open, modify entry, change note field, submit change, pick file/exit, etc.).

**Comment by mithrades** [comment]
The pre160 branch has only returned PG to the operating behavior it was before the Tcllib 1.17 update, that is retaining the changes to the database but having to close PG with the NO button in the closing dialog for saving or dumping changes.

My settings under Preferences:
General tab: edit login (double click), all three boxes selected for Backup database on save, Remember sizes of dialog boxes, Use Gorilla auto-copy.
The Defaults tab: Auto-save database immediately when changed selected, Use Password Safe 3 format selected, V2 Unicode not selected, Time stamp backup not selected.
Export tab: no boxes selected.
Display Tab: only Iconify upon auto-lock
Browswer Tab: no selections

Password Policy 8 characters with all boxes selected except the last, Use easy to read characters etc

To create this 'loop' I open a database and add a login or edit and modify a login as soon as I close the edit box PG saves the changes and I receive an OK box that I click on to close. 

When I exit out of the database I get the box with the yellow triangle that tells me the current password database is modified Do I want to save the database or not. If I click on the Yes button I see the saving progress graph but PG stays open. If I exit again I get the box with the yellow triangle and once again asking if I want to save the changes or not. If I press Yes then the box goes away but PG continues to stay open. If I click on the No button PG closes but the changes are saved.

PG has been working like this for a long time maybe two years, I just got used to it and didn't worry having to select the NO button to close it because it always reliably saved the changes anyway. until it stopped saving changes (apparently after a recent TCllib update)

**Comment by rich123** [comment]
Hmm - you get an "ok" dialog after the auto-save has completed?

What, exactly, does this "OK" dialog that appears state?

**Comment by mithrades** [comment]
OK I think I've solved the problem by noticing that the backup path was to a directory I had made as an extra storage unit that I didn't actually open because this directory has only su permissions. I changed the backup directory (path) in PG to the same directory the database I was opening (with user permissions) and then did an edit that was duly saved without an OK box popping up and the changes were duly saved. (and you will like this) The backup file corresponded to the backup path I had changed (corrected) and voilà PG closed normally having been able to use a backup path that corresponded to the same directory (and permissions) as the database. I see now for the last two years odd I've been trying to backup to a directory I only had 'read only' permissions. with the database I was opening.

My conclusion is this issue is personal to me that's why you couldn't replicate it, and the issue should be closed.

**Comment by rich123** [comment]
Now that I know the trigger - I can also reproduce it.

That empty dialog box is a problem - I'll have to do some instrumenting to see where it is being drawn from and fix the fact that zero text is being inserted into it.  So, indirectly, you did find a small bug.

**Comment by rich123** [comment]
Fix pushed - the dialog, if it appears due to lack of permissions to write to the backup path, now contains an error message instead of no text.
