### ISSUE TITLE
Password Gorilla OS X damaged and cannot open - kind of

### ISSUE THREAD

**Issue by dspruell** [zdia/gorilla#154]
Seeing Gatekeeper issue behavior similar to #130 again, but am only partially able to work around the Gatekeeper warning in this case.

- OS: OS X 10.10.5 Yosimite
- Download: http://gorilla.dp100.com/downloads/gorilla.mac.15373.zip
- SHA256: 51c443fb58a3628c2a45bd3160096abb9b017f33e6a08628636168f996ad0414
- Gatekeeper setting: Allow apps downloaded from: *Mac App Store and identified developers*

Extract the program bundle from the Zip in finder, and double click file to open. It displays the expected untrusted code from Internet message:

> **"Password Gorilla.app" is damaged and can't be opened. You should move it to the Trash.** 
> Firefox.app downloaded this file ...

Either of two solutions should work at this point:

1. Disable Gatekeeper:
    * From System Preferences, change the Gatekeeper setting to allow apps downloaded from anywhere
    * Double click program to launch the first time
    * Re-enable Gatekeeper protection
2. Temporarily distable Gatekeeper for the program only
    * Hold Control and click the program
    * Select **Open**
    * Open the file when prompted

However, on two systems I've tried, the second solution is not working - only the first. When Command-clicking the file and selecting Open, the same "damaged and can't be opened" dialog is displayed. Only disabling Gatekeeper from System Preferences allows the program to be run.

Referring to https://support.apple.com/en-us/HT202491 *(OS X: About Gatekeeper)*:

> "Damaged" app. – The app has been altered by something other than the developer. This message will appear no matter the Gatekeeper option chosen.
>  "App name" is damaged and can't be opened. You should move it to the Trash.

Checking with *codesign(1)*:

```
$ codesign --verify Password\ Gorilla.app
Password Gorilla.app: invalid Info.plist (plist or signature have been modified)
In architecture: x86_64

$ echo $?
1
```

I'm unsure if this has to do with the issue.

It's odd that the Control-click option for working around Gatekeeper doesn't seem to work in this case. Are others seeing this? 

Is there a possibility we could see proper code signing on Password Gorilla? It's a good application but this seems like it may be a long-running barrier to entry for some users.

**Comment by rich123** [comment]
> It's odd that the Control-click option for working around Gatekeeper doesn't seem to work in this case.

I'll let others who have a Mac and can verify chime in, but I do wonder if maybe Apple changed something in 10.10.5 such that the control+click method of "allow this program" no longer works.

> Is there a possibility we could see proper code signing on Password Gorilla?

If it is possible to do the code signing on Linux, then it is possible.  If a Mac is required, then this is made much more difficult by the fact that I do not have a Mac to use to do the code signing upon.

> codesign --verify Password\ Gorilla.app

Since the Gorilla kit is not signed at all, asking codesign to verify it will of course fail.  I am curious, however, if you extract the "gorilla.aqua" executable from the zip, what happens if you try to launch it via the control+click/open method (or is this how you are launching it)?

**Comment by rich123** [comment]
> Is there a possibility we could see proper code signing on Password Gorilla? It's a good application but this seems like it may be a long-running barrier to entry for some users.

I would very much like to find a way to sign the gorilla Mac packages such that they do not trigger this message.  But some Google searches imply that a Mac is a required element to be able to sign apps to bypass gatekeeper.

**Comment by rich123** [comment]
Just found this quote here http://stackoverflow.com/questions/4833052/how-do-i-remove-the-extended-attributes-on-a-file-in-mac-os-x:

> Just remove the com.apple.quarantine attribute. It works even if you don't have an administrator account, which can be a plus. After that, the app isn't considered "downloaded" and is therefore not blocked.

What happens if you remove the extended attribute from the gorilla app bundle (and/or from the *.aqua file inside)?

$ xattr -d com.apple.quarantine gorilla.mac.15373.zip

**Comment by bellbrad13** [comment]
FYI - If you download the file gorilla.mac.15373.zip, unzip it, and run the xattr command on the bundle, it gets around Gatekeeper and you can then double-click (or whatever your preference of launching it is) without changing or setting anything within System preferences.
I just tried again with a fresh download on El Capitan - broken before using xattr and works fine with no other modifications except for running this from Terminal:
xattr -d com.apple.quarantine Password\ Gorilla.app/

**Comment by rich123** [comment]
@bellbrad13 Thanks for the confirmation that deleting the extended attribute disables Gatekeeper for a new Password Gorilla download.  I will add a note to the wiki and to the download archive site about using xattr from Terminal to turn off the Gatekeeper check.

**Comment by rich123** [comment]
@dspruell - does the "xattr -d" method work around Gatekeeper for you?

I have added additional details to the Github wiki and added a Gatekeeper info page to the download site (http://gorilla.dp100.com/downloads/MacOS-Gatekeeper.html) with details of the known Gatekeeper bypass methods.

**Comment by dspruell** [comment]
@rich123 - in my case, when the archive is extracted, the Mach-O (.aqua) file can be launched _without_ doing anything to bypass Gatekeeper (with Gatekeeper enabled, and even though the com.apple.quarantine attribute is present on the file, which is... interesting):

```
$ unzip gorilla.mac.15373.zip
Archive:  gorilla.mac.15373.zip
   creating: Password Gorilla.app/
   creating: Password Gorilla.app/Contents/
  inflating: Password Gorilla.app/Contents/Info.plist  
   creating: Password Gorilla.app/Contents/Resources/
  inflating: Password Gorilla.app/Contents/Resources/Gorilla.icns  
   creating: Password Gorilla.app/Contents/MacOS/
  inflating: Password Gorilla.app/Contents/MacOS/gorilla.aqua

$ ls -l@ Password\ Gorilla.app/Contents/MacOS/gorilla.aqua 
-rwxr-xr-x@ 1 dspruell  staff  5835901 Oct 27  2014 Password Gorilla.app/Contents/MacOS/gorilla.aqua
	com.apple.quarantine	     26

$ ./Password\ Gorilla.app/Contents/MacOS/gorilla.aqua
<program launches without issue or prompt>
```

Here is a readout of extended file attributes on the extracted app bundle showing the quarantine attribute on all contents:

```
$ ls -Rl@ Password\ Gorilla.app
total 0
drwxr-xr-x@ 5 dspruell  staff  170 Oct 27  2014 Contents
	com.apple.quarantine	 26 

Password Gorilla.app/Contents:
total 8
-rw-r--r--@ 1 dspruell  staff  860 Oct 27  2014 Info.plist
	com.apple.quarantine	 26 
drwxr-xr-x@ 3 dspruell  staff  102 Oct 27  2014 MacOS
	com.apple.quarantine	 26 
drwxr-xr-x@ 3 dspruell  staff  102 Feb 27  2012 Resources
	com.apple.quarantine	 26 

Password Gorilla.app/Contents/MacOS:
total 11400
-rwxr-xr-x@ 1 dspruell  staff  5835901 Oct 27  2014 gorilla.aqua
	com.apple.quarantine	     26 

Password Gorilla.app/Contents/Resources:
total 112
-rw-r--r--@ 1 dspruell  staff  53641 Oct 12  2010 Gorilla.icns
	com.apple.quarantine	   26
```

I can confirm too that running `xattr -d com.apple.quarantine` on the top-level bundle directory is enough to allow the app to launch. It only clears the attribute on the top level directory, which leaves com.apple.quarantine set on the contents of the app bundle - but it's enough to run the software. If for any reason having that attribute cleared from the entire software bundle is required, a recursive option can be used to remove the attribute from the entire set of files/directories; not sure if this is the best way to go as most comprehensive, or if unnecessary:

    xattr -rd com.apple.quarantine Password\ Gorilla.app

Also disabling Gatekeeper and running the app the first time to accept the "Open" prompt doesn't remove the attribute from any part of the app bundle at all, which I thought it would. Just an observation.

**Comment by rich123** [comment]
> $ ./Password\ Gorilla.app/Contents/MacOS/gorilla.aqua
> <program launches without issue or prompt>

I have a guess as to why the above may work, and as it is a guess, I very well may be wrong.

Gatekeeper only functions via launching from the OSX GUI, not when launched directly from the terminal CLI.  

If you are willing to do a bit more testing, try copying the .aqua file from the bundle to your desktop directory (so it should then appear as a desktop icon) - and then try to launch the .aqua file from the GUI by double clicking it.

If you get a gatekeeper error, that lends weight to my guess that Gatekeeper is integrated into the GUI launch sequence.

> [recursive attribute removal]

Removing all the quarantine attributes recursively should not cause any harm, and would be worth keeping mindful of in case a future update to MacOS changes to looking at the attribute on the actual executable (or on any other files underneath) instead of on the top level bundle directory.

In the meantime, attribute removal is reasonably easy to accomplish in order to work around Gatekeeper, given that everything I seem to find regarding Apple app. signing all appears to indicate that a Mac running MacOS is pretty much required to successfully create a Gatekeeper approved signed bundle directory.

**Comment by dspruell** [comment]
Attempting to launch the .aqua file by double-clicking from the GUI (either in a Finder window, or from Desktop) fails as .aqua is not a recognized extension for the launcher (displays dialog "There is no application set to open the document...."

**Comment by dspruell** [comment]
Closing given that documentation update done.
