### ISSUE TITLE
Don't raise window on timeout (at least optionally)

### ISSUE THREAD

**Issue by Keith-S-Thompson** [zdia/gorilla#155]
Password Gorilla automatically locks after 5 minutes (the timeout is configurable).

That's great, but when it locks the window is raised to the top.  I'm typically doing
something else; the automatically raised window interrupts what I'm doing and starts
grabbing keyboard input.

This happens when the window is minimized and when it's merely behind my current window.

Platform: Ubuntu 14.04.4 LTS, x86_64, Cinnamon desktop.
Password Gorilla: 1.5.3.7-1 (also happens with the current version from GitHub).

**Comment by rich123** [comment]
First question: Do you have the preference setting "Iconify upon auto-lock" that is inside the "Display" tab of the File->Preferences dialog turned on or turned off?

Because your description sounds to me that when Gorilla auto-locks, you end up with a Password Gorilla lock window in view on top of everything else.  That is what occurs if "Iconify upon auto-lock" is turned off.

If the "Iconify upon auto-lock" preference is turned on, then when PWGorilla auto-locks from the timer it should also set itself to be just a background icon rather than a foreground lock window.

If you have this setting off, please try turning it on for a bit and see if having it turned on cures the issue for you.

**Comment by Keith-S-Thompson** [comment]
Ah, I didn't know about that setting. That certainly solves at least 99% of the problem.

I'm still slightly concerned that the window appears in the foreground for a fraction of a second before being minimized. It's visually mildly annoying, and I'm a little concerned that it might steal a character or so of keyboard input before it minimizes if I happen to be typing at the time. (I haven't actually seen it steal any input.)

Meanwhile, I'll certainly keep that option on. Thanks.
