### ISSUE TITLE
Problem at running gorilla 1.5.3.7 in Windows 7... (dependent library not found in the library path)

### ISSUE THREAD

**Issue by dsfb** [zdia/gorilla#158]
Hi, zdia.

I was trying to run Password Gorilla, but it failed with the following log text file:

[gorilla1537_error_09082016.txt](https://github.com/zdia/gorilla/files/409421/gorilla1537_error_09082016.txt)

.

Best Regards,
dsfb.

**Comment by rich123** [comment]
Are you trying to run the pre-packaged executable or directly from the source?

From the log, it looks like you are trying the pre-packaged executable, it also looks like it is the 64-bit executable.

Is your Win7 system a 64-bit system?

**Comment by dsfb** [comment]
I am trying to run the pre-packaged executable.

Yes, my Win7 system is a 64-bit system.

**Comment by rich123** [comment]
What I just tested:
1) download the windows 64-bit executable from here: http://gorilla.dp100.com/downloads/gorilla1537_64.exe
2) try running the freshly downloaded copy on the one 64-bit win7 system I have access to

The executable launched without issue.

The win7 system is Win 7 Enterprise - SP1 and according to the control panel/system window is running in 64-bit mode.

Is your win7 system running a newer service pack?  I ask because part of the error message says "this library or a dependent library could not be found in library path".  It may be possible that the error is due to the "or a dependent library" part of the message.  Unfortunately at this time I can only guess what that dependent library might be.  I'll have to see if there is a way to determine library dependency on a windows system.

**Comment by dsfb** [comment]
I tested it today, and the same error occurred.

I attached the following log file in this comment.
[gorilla_1537_15082016.txt](https://github.com/zdia/gorilla/files/418082/gorilla_1537_15082016.txt)

The error described in this log file is about the "Temp" directory that is a subdirectory of the "C:/Users/daniel.bruno/AppData/Local" directory, of course. By the way, it  can't load the library "itcl34.dll, but it doesn't appoint any error.

The line "Failure to load package: Itcl" is important...

I expect you can fix this error, please...

The machine is in my job office, that is, it is for business purposes.

Best Regards,
dsfb.

**Comment by rich123** [comment]
> I tested it today, and the same error occurred.

Did you test with a fresh download - one that you verified matched the GPG signature of the file on the download site?

If you did not download a fresh copy, *and* verify the GPG signature, then please try that next.  I suspect you will get the same error, but doing so will remove one variable (a potentially corrupted file) from the equation.

Have you been able to run any previous version of PWGorilla on this specific machine?

If yes - does that prior version still work?

> The error described in this log file is about the "Temp" directory that is a subdirectory ...

Yes, that is the manner within which TclKit's load binary object modules.  They transparently copy the .dll out to a temp directory, then load from there (because the host OS can not look inside TclKit format archives).

> By the way, it can't load the library "itcl34.dll, but it doesn't appoint any error.

That "no error" message is from Windows.  It often means that itcl34.dll has a dependency upon a standard Windows .dll, and that standard Windows .dll is not installed.  Unfortunately, since Windows does not report which dependent library was missing, there is zero info to use to work out a solution.

> The line "Failure to load package: Itcl" is important...

Yes, it is what Tcl can report, since Windows does not provide it any useful information.  And it is in almost all instances like this a symptom of a missing Windows system .dll file, or of a very aggressively locked down Windows security setup.

> I expect you can fix this error, please...

I can not fix that which does not occur on the Windows 7 system I have access to.  Further, Itcl is a standard Tcl library, it is merely used by Gorilla, but the authors of Gorilla did not write the Itcl.dll library.  So whatever is going wrong is somewhat deeply embedded in the Tcl system, not within Gorilla's actual code.

> The machine is in my job office, that is, it is for business purposes.

Understood.  Have you been successful with any prior Gorilla version on this exact same machine and OS?  If yes, as a temporary measure I would suggest you consider using that prior version for the moment until more can be deduced about this version.

Also, can you try one of these two alternatives below:

1)  Go to this webpage here:
http://kitcreator.rkeene.org/kitcreator
Select the following options:
KitCreator Version 0.9.5 (should be the default)
Tcl Version: 8.5.15
Platform: Windows/amd64
Check the box next to "Package [incr Tcl]"
Kit Storage: Automatically Determined

Then push the "Create" button.  The tool will take some time, then download a tclkit.exe file to you.  

or 

2) Download the tclkit.exe I just created from the above options and placed here:
https://gorilla.dp100.com/downloads/tclkit.exe
sha256sum of the above tclkit.exe is cea77e8af308bd88765b29079871f706e7a52026c294eb4ca993e14a71988ac3

Once you have a tclkit.exe via one of the two methods above, then put that tclkit.exe onto the machine that does not launch PWGorilla.

Next, run that tclkit.exe file (you will see a terminal window appear with a % sign as a prompt).

In the terminal window, type the following exactly, including case of the letters:

package require Itcl

You will get one of two outcomes:

1) the string "3.4" will be printed - this is the good outcome;

2) an error message about unable to load Itcl - this is the bad outcome.

If you get the good outcome, then this is a possible path to fixing the issue for you, I can generate a Tclkit via the kitcreator and wrap 1.5.3.7 into it, and it should then work for you.

If you get the bad outcome, then the problem is some Windows system .dll that is missing from your Windows install on this machine that Tcl's Itcl code depends upon (i.e., requires).  The only real solution there would be to determine what is missing (I do not know how to determine this on a windows machine) and then install yourself or have your workplace install the missing Windows system .dll's that Tcl/Itcl depends upon.

**Comment by dsfb** [comment]
Hi, rich123.

I tested the downloaded file with gpg, but it showed good signature for that file.

I downloaded the tclkit.exe file that you created for me, and it worked well because the string "3.4" was printed when I typed the following exactly: "package require Itcl"...

By the way, you can generate a Tclkit via the kitcreator and wrap 1.5.3.7 into it, for me, please.

Best Regards,
dsfb.

**Comment by rich123** [comment]
It is good news that the KitCreator version loaded Itcl.  That means it is somewhat probable that the executable below will work for you.

https://gorilla.dp100.com/gorilla-1.5.3.7-v1.5.3.7-29f77ae81ad03c94fc9112d01d958662bb1d202d-win64.exe.sig

https://gorilla.dp100.com/gorilla-1.5.3.7-v1.5.3.7-29f77ae81ad03c94fc9112d01d958662bb1d202d-win64.exe

This executable works on the Win64 system I have access to - but then the original download also worked on that system, so knowing it works there is not determinative as of yet.

**Comment by dsfb** [comment]
Thanks, rich123.

This file worked well for me. Link for this file: [https://gorilla.dp100.com/gorilla-1.5.3.7-v1.5.3.7-29f77ae81ad03c94fc9112d01d958662bb1d202d-win64.exe](url)

By the way, if you want... then you can close this issue.

Best Regards,
dsfb.
