### ISSUE TITLE
Is there a way to deactivate window auto-focus when auto-locking?

### ISSUE THREAD

**Issue by aalexgabi** [zdia/gorilla#165]
Every time the Gorilla Passwords auto-locks (due to the lock timeout), the window gets auto-focused, interrupting the typing flow. This really becomes annoying after a couple of months. Is there a way to change this behavior?

**Comment by acidjunk** [comment]
I never noticed this on the OSX version.

**Comment by aalexgabi** [comment]
I forgot to mention that I'm using Ubuntu 14.04 with Gnome Shell.

**Comment by rich123** [comment]
What version of PWGorilla are you running?

What choice have you made for the File-> Preferences-> Display-> Iconify upon auto-lock preference setting?

**Comment by aalexgabi** [comment]
@rich123 Thank you for your suggestion. Once I checked "Iconify upon auto-lock" Gorilla Passowrd does no longer auto-focus. I saw it before posting this issue but I did not realize it can be related so I didn't check it.

Would it be interesting to rename this option to allow the user to understand that once activated the app will no longer auto-focus? I'm thinking on something like: "Iconify upon auto-lock (disables window auto-focus)". Would it be interesting to add another option specifically for this? Does this work in the same way on all systems?

I am closing this because this has been answered. Feel free to reopen if you want to make any adjustments.

**Comment by rich123** [comment]
> Would it be interesting to rename this option to allow the user to understand that once activated the app will no longer auto-focus?

No, because the option is only tangentially related to the issue you were having.  Which application on your desktop receives focus is the responsibility of the window manager running, and PWGorilla does not have control over your window manager.  You likely saw this issue because your Gnome system is likely set to give keyboard focus to whichever window happens to be "on top" of everything else, and when PWGorilla auto-locks, the locked window became the current "on-top" window from your window managers point of view, and so it (the window manager) gave the PWGorilla window focus.

By iconifying the PWGorilla window instead, the window manager no longer views it as "on top" and so it will return (or maintain) focus on whatever was focused before PWGorilla locked itself.

> Would it be interesting to add another option specifically for this?

No, this is not possible because there is no way for PWGorilla to control the focus transfer behavior of your window manager.  The most that could be done is to add some additional documentation text stating that this option might be helpful sometimes in situations of focus transfer to PWGorilla when it automatically locks.

> Does this work in the same way on all systems?

No, it does not, because it depends upon the focus transfer settings of the window manager being used on the system.  Someone running Fvwm2 in "ClickToFocus" mode would never have focus transfer to PWGorilla when it auto-locks, regardless of the setting of this option.  Alternately, someone running Fvwm2 in "GrabFocus" mode would always have the focus transfer to PWGorilla, regardless of the setting of this option.
