### ISSUE TITLE
CLI utility to print  Password Gorilla database files. (pwsafe)

### ISSUE THREAD

**Issue by nobicycle** [zdia/gorilla#172]
pwsafe.org shows Password Gorilla and pwsafe as clients.
I am looking for a command utility to print values from the  same database as Password Gorilla. 
I attempted to use pwsafe  to access Password Gorilla database files, but get the following error:

> $ pwsafe -v --list -f /tmp/Gorilla.psafe3 
> rng seeded with 1024 bytes from /home/adrian/.rnd
> Enter passphrase for /tmp/Gorilla.psafe3: 
> Passphrase is incorrect
> Enter passphrase for /tmp/Gorilla.psafe3:

$pwsafe -V
pwsafe 0.2.1beta

https://github.com/nsd20463/pwsafe

**Comment by rich123** [comment]
See Issue #8 for "pwsafe" (https://github.com/nsd20463/pwsafe/issues/8).

Specifically this part:

pwsafe only works with Version 1 or Version 2 databases. Not Version 3.

Your Password Gorilla file is most likely version 3 (as Gorilla prefers V3 files unless you try really hard to make it do otherwise).

To get it to create a V2 file you'll have to:
1) uncheck the "use V3 format" setting in the defaults tab of the preferences pane
2) create a new database
3) add the passwords you want to use to the new db (merging in your V3 DB should work)

Then you should have a V2 DB that will work with pwsafe.  But note that V2 does not contain many of the newer nice items that V3 does, and V2 is not as secure as V3.

Otherwise, this is really a bug/feature request for pwsafe, it (pwsafe) should be upgraded to consume V3 files.  And it's README should really be updated to make the fact that it can't read V3 files clear.

**Comment by rich123** [comment]
Further, what is it you are really trying to accomplish?  Adding a minimal CLI utility to PWGorilla should not be that hard, as the read/write code for pwsafe files is a loadable module, so it is already setup to be loaded into a CLI tool as well.

**Comment by nobicycle** [comment]
All noted. Thank you rich123
