### ISSUE TITLE
Password Manager fails to sync on iPad/iPhone (sync error 400)

### ISSUE THREAD

**Issue by Spinoza1900** [zdia/gorilla#174]
Hi,
Password Manager suddenly will not sync anymore from Apple mobile devices to psafe3-file in Dropbox.
It says: "sync error 400"
Tried 'unlink from Dropbox' and reconnect. Reconnect is not possible. When I try to reconnect, it says: "Error listing directory. Dropbox error 400"

pwSafe version 6.4.2.
Syncing via Dropbox
Device: iPad2,4
iOS version 9.3.5.

**Comment by rich123** [comment]
Unless there is some compatibility/emulation layer that I am unaware of, this is likely, as I do not own any Apple devices, Password Gorilla is not compatible with iPad/iPhone devices.  So unless you actually meant "Apple Mac Laptop" I know of no way you could have been using Gorilla on an iPad/iPhone, so this issue should be directed to whatever application you are using on the iPad/iPhone instead.

If instead you actually meant "Apple Mac Laptop", then "sync error 400" sounds very much like an error from dropbox, not PWGorilla.  I.e., PWGorilla is saving to the file that is synchronized into dropbox, but dropbox is what is reporting "sync error 400".  Gorilla does not do any native sync with dropbox at all.  In fact, Gorilla has no knowledge that its password store is saved into a dropbox folder.  It just opens a file on what it believes to be the local disk and saves content into the file.  Any sync. operation would be caused by dropbox, and any error in sync. operation would also be the fault of the dropbox client (or server, I can't say as I don't use dropbox myself).

**Comment by rich123** [comment]
Ah, upon sending the above I note you stated at the bottom that you are using "pwSafe version 6.4.2.".  Whatever issue you are having is with either "pwSafe version 6.4.2." (and PWGorilla is not "pwSafe version 6.4.2") or with dropbox.  You should send this report to one (or both) of those tools instead.
