### ISSUE TITLE
Save button missing

### ISSUE THREAD

**Issue by ciampix** [zdia/gorilla#187]
I am a very satisfied user of gorilla password. I use it on a day by day basis.
Since I use it very often, the list of passwords and logins in my archive are grown so much that now I cannot see the red string that appears in the top of the list indicating that it archive need to be saved. This happens because the red warning is buried in top of the list, as I see only in the central view of it, centered on the currently edited login record.
Here I am suggesting to add a button on the top menu (on the right?) that should change color to indicate the need to save the archive. Clicking on it should save the archive and make the button change color back to the bar color, to indicate the return to the normal operational status.

**Comment by MUHeinz** [comment]
I use security - customize... - Auto-save database immediately when changed

usualy ctrl-s save the database also


Am 26.06.2018 um 10:26 schrieb Marco Ciampa:

**Comment by ciampix** [comment]
>  The other option would be to use a small amount of the bottom status bar for a "not-saved" indicator, and that would work on all platforms because that bar is fully drawn by Gorilla.

Great idea!
The rational behind this is to make clearly visible that there are unsaved modifications and help the user quickly save these modifications.
In the meantime I switched on the auto-save feature even if it is not always what someone wants to do, so I also enabled the timestamp function just for this reason...

**Comment by rich123** [comment]
Just pushed commit 6139bbba868fa879132473a85bd41cbba1adeaa2.

It is a small change from your initial suggestion.  Instead of an extra indicator inside the main GUI the titlebar text changes from "Password Gorilla - filename" to "Password Gorilla - (Changed) - filename" when there are unsaved changes present.  This provides for the alerting aspect that does not scroll away.  Then you can use File->Save or "Ctrl+S" to save the changes when ready to do so.

If you can run the source, please download a copy of that commit and test it locally and let me know if you find any issues.

**Comment by ciampix** [comment]
It works... definitely it is an improvement! Thanks!

**Comment by ciampix** [comment]
I still miss a save button but I can close this for now...

**Comment by ciampix** [comment]
Why not change the title bar color to signal unsaved changes?

**Comment by acidjunk** [comment]
I don't know if you change title bar under OS X (and with older Unity based Ubuntu's it's also not possible)

**Comment by rich123** [comment]
@ciampix: 

> Why not change the title bar color to signal unsaved changes?

Several reasons:

1) Under Linux/X11, the title bar of windows is owned and managed by the window manager, not the app., and there is no interface for an app. to make those changes.

2) I don't know about MacOS, but I'd guess that a similar situation exists, the "title bar" color of a window is likely not under the control of the app. running in the window.

3) The Tk GUI library provides no interface to make title bar color changes (likely because most windowing systems don't give out an API to do so).

4) Simple color change, unless *very* carefully done, is not at all helpful to colorblind individuals.  This was one big reason why the current commit changes the text of the title bar (for which an API interface is provided by Tk).  The text change is visible for both colorblind and non-colorblind individuals.

I'm still thinking about adding a small indicator in the corner of the status bar that will appear when unsaved changes exist, and clicking it would initiate a save.  I simply have not had any opportunity yet to expend time towards that goal.

**Comment by rich123** [comment]
@ciampix:

> window background color?

That could be done, as the background of the GUI elements is under Tk's control.  But just a color changing background would still have issues for colorblind individuals, so I'd need the "indicator button" I referenced above to provide a full fix.

And a color changing window background is something that some percentage of uses may not wish to have happen, so adding color changing backgrounds is not simply "change color when dirty".  It also involves wiring it into the preferences subsystem as another preference, and adding a checkbox somewhere in the preferences panel to allow those who do not want it to turn the feature off.  Not impossible to do, but it is more effort than just a one line change to the code that already colors the top line of the tree red when changes exist (which, itself, is also not very colorblind friendly, but has been present since before my time here).

Now, while writing the above paragraph, a thought for another variant occurred to me.  Instead of coloring just the top line of the tree red, color the entire tree of password entries red when there is unsaved data.  This would still need a preference to allow turning it off by those who would prefer not having it happen.  And it does not yet fix the colorblind issue, but this would be the smallest change overall.

**Comment by rich123** [comment]
@ciampix:

> the thing is... sometimes you close your PC. Sometimes some apps block the shutdown signalling that they need to save their date, but sometimes this won't happen (say you run out of your battery charge or simply your OS ignores the apps or some other reason). Prevention is better than cure...

Unfortunately, Tcl/Tk provides no interface to whatever API it is that windows uses to allow app's to block a shutdown.  And such a subsystem does not exist in the Linux world.  I don't know if MacOS allows app's to forstall a shutdown if they have unsaved changes or not, but again, there is no Tcl/Tk API to interface to it, so it is not a feature Gorilla can make use of.

But your reasoning above is exactly why the "save database immediately upon changing" option in the preferences was added (I think zdia was the one who added the feature long ago).  If Gorilla does an immediate save the moment a change is made to any entry, then closing PC, running out of battery, mains power failure, etc., simply have no effect on unsaved changes, because there are never any unsaved changes to be effected.  And when Gorilla does do the save, it does so by creating a new file first, then renaming it over top of the previous file (unless the "timestamp" option is on, then the old file gets renamed to a timestamped backup file) so provided ones filesystem does provide the basic POSIX guarantee of a rename of one file on top of another being transactional, one of the two versions is supposed to exist after any of those shutdown occurrences, so there should be very little chance for lost data even if the battery loss/power loss occurred during a save operation.

**Comment by ciampix** [comment]
Thank you _very_ much @rich123  for your effort to listen to my rants and for trying to make them sound sensible! I am really appreciating that! BTW IMHO the idea to make all unsaved text red is really a good one!

**Comment by rich123** [comment]
Yes, you may proceed.
