### ISSUE TITLE
Interface is always locking even if lock when idle is 0

### ISSUE THREAD

**Issue by pusheax88** [zdia/gorilla#188]
Hi!

I use password gorilla 1.5.3.7. In Preferences I set option Lock when idle after = 0 (0=never).
The program still locks after 5 minutes. Is there a workaround?

**Comment by rich123** [comment]
If you mean you made the change in "File->Preferences", then that setting sets the default for new databases.

The 'timeout' time is a metadata item that is stored in the password safe encrypted file (I suppose the reason being that different databases can have different auto-lock times dependent upon the security importance of the items stored therein).

Because of this, if you want to change the timeout for an existing database, you need to use the Security->Customize menu (after opening the DB file you wish to modify).

**Comment by pusheax88** [comment]
Rich, problem solved. Thanks a lot!
