### ISSUE TITLE
New behavior of nautilus file manager breaks gorilla autocopy

### ISSUE THREAD

**Issue by PorcelainMouse** [zdia/gorilla#194]
Is anyone else on Linux seeing this?  When nautilus is running, gorilla autocopy doesn't work because gorilla thinks everything it copies to the clipboard is immediately pasted and gorilla copies the next thing.

I'm not saying it is a bug in gorilla, but if there is a way for gorilla to work in this environment, that is likely the only solution.

**Comment by rich123** [comment]
This sounds like Nautilus is either generating a "paste" event when it sees the clipboard change, or it is trying to claim permanent ownership of the clipboard for itself at all times.

The first would mean it has likely incorporated functionality similar to the 'xcutsel' and/or 'xclipboard' commands while the second would mean it is just being a bully (and the second should be considered a bug on Nautilus' part, although how the Gnome dev's normally take to bug reports it would likely be dismissed as "functioning as we intended, go away".

I've avoided (so far) trying to work out some way to avoid this issue (for the simple reason that closing 'xcutsel' or 'xclipboard' down is easy.  But if Nautilus is going to start being an 'xcutsel' or 'xclipboard' clone, unless there is a configuration setting to ask it to leave the clipboard alone, then I may have to begin experimenting with ways to try to detect when this happens.

However, even detecting it is not easy.  All Gorilla knows is "some other app requested the clipboard contents".  The only way I've ever come up with to detect is by the speed at which the paste event occurs.  Too fast likely means a running program grabbed the clipboard contents.  But there's a fine line between detecting 'too fast' by a program and a very quick user performing a paste.  I fear the detection would fail enough times to also become an irritant.  

So my first question is to ask: "is there an option to disable this new feature?"

If the answer is no, then the good news is I can test my theories for detecting the apps doing this, since I can run xclipboard or xcutsel and have exactly the same effect occur.  What I can't say yet is that I can work around the issue.  That will take some experimenting to see if it is possible to detect without too many false detections (or non-detections).

**Comment by rich123** [comment]
FWIW I do have this same thing happen when I'm running a VNC link into my desktop.  VNC tries to provide for clipboard handling over the VNC connection and it produces the same effect.

One solution (although far from perfect) is to open a "view" window on the password entry after right clicking.  If you are running a version of the pre160 branch that includes the changes for making the username and password rows in the "view" menu clickable to cause a clipboard copy action, then you can double click on those items to trigger a one-at-a-time copy/paste without having to turn off auto-copy globally.

Granted, as I'm not running VNC full time, an occasional "workaround" like this is not too bothersome.  For someone who likely might have a copy of Nautilus up all the time, it is way less than ideal.

**Comment by PorcelainMouse** [comment]
I follow you completely.  I've reported this to GNOME.

https://gitlab.gnome.org/GNOME/nautilus/issues/729

No, there is no way I've found to disable this behavior and I included that in my bug report.

I'm not sure which it is, either.  I assume it isn't the latter case as that seems extreme, even for GNOME.  But, whatever it is doing, it's doing it continuously, since it happens less than a moment after I initiate the autocopy.  And, I cannot think of any good reason to beat on the clipboard with paste events all the time.

I can think of many reasons no one has tackled this problem before.  For one, it's not been a problem before.  But also, this behavior doesn't seem very useful, so why you think of it.

Well, I've had this new nautilus for just a few days, now, and I have to close it after every single time I use it. It's not an impossible workflow, but also quite clearly much less convenient and less sensible.  Normally...by which I mean as long as I have used computers...I just leave the file manager running, once I open it.  In Windows you all but have to have it open all the time.  In linux, I use the command line way more.  So, I'm one of the people you mention at the end of your post.   I cannot imagine this will satisfy for long; something will have to give, soon.

I'm always happy to help troubleshoot or test.

**Comment by rich123** [comment]
Good on the report.  Whether it will actually result in a change is yet to be seen.

I hope the 'reason' is #1, but I don't rule out #2 (yet), Nautilus is from Gnome, and the Gnome dev's have a lengthy  history of "this is the way we have decided that you shall do things, if you don't like it then go away" responses.

The part that adds weight to this, hopefully, being unintentional is that a GUI files manager is an odd place to include a 'xcutsel' or 'xclipboard' clone function.  Those two bits of functionality just don't seem to have anything in common to justify them being together in the same app.  At least not without a really interesting definition of "common functionality".

The X apps (xcutsel and xclipboard) have a usefulness to them.  Xcutsel helps to interface between apps that only understand X clipboard and other apps that only understand X selections (but this is less of a problem today as most modern apps for X handle both now).  Xclipboard provides a 'history' of various copies made by a user and allows one to pick the items to 'paste' elsewhere as one sees fit.   I could see usefulness here in the days of smaller screens where having to raise/lower apps to copy/paste between them is painful (instead, just select everything up front in one, switch to the other, then start pasting pieces back in).  And VNC's behavior is at least meaningful in that it is attempting to provide seemless integration between the remote desktop and the local desktop which can also be useful.

In the interim, is there an alternate GUI file manager that you could install and utilize instead of Nautilus?  If the alternate did not include this functionality (and it very likely would not) then you can avoid the issue in that way for the moment.  This is not perfect, however, because if this is an intentional change on Gnome's part, there will be more reports of this happening as other users upgrade into the Gnome version with this new feature.

**Comment by PorcelainMouse** [comment]
Again, complete agreement on all points.  I don't see why this behavior makes sense for a file manager.  But, GNOME team says there was a deliberate change with the clipboard.  I'm assuming that is the source of this issue.  I hope they can determine the implementation was unnecessarily broad and that they can get what the want by doing it some other way.  And that they choose to change it.  Or, that it is very easy to make it configurable, which would also be satisfactory.

I could fall back to Thunar, yes.  That occurred to me last night, too.  I will probably end up doing that until these bugs are closed.  But I use Xfce DE, so that is more sensible for me than most people.

**Comment by rich123** [comment]
Well, I do have good news to report.  I hacked in a very rough experiment of my idea for monitoring the elapsed time between a copy and paste operation and skipping copying the password when the paste occurs "too quickly" and it seems to work around the issue quite nicely.

Now I just need to find some time this weekend to code out a proper implementation rather than my quick experimental hack to test the theory.

**Comment by rich123** [comment]
> But, GNOME team says there was a deliberate change with the clipboard. I'm assuming that is the source of this issue.

The answer given, and the commit referenced, show they did change how the GUI file manager handles the clipboard.  While it could be reasonably argued that when it had ownership that checking for pastes was an ok idea (it really was not, X11 copy/paste is event driven, yet they almost look to be polling, which would waste power in a battery operated environment), broadening out that test to "any clipboard contents, no matter what app was using the clipboard" was really the wrong way to go there.  But I, sadly, have no expectation that they will see their change as an error and revert it.

**Comment by rich123** [comment]
@PorcelainMouse, please test this change if you can.

**Comment by PorcelainMouse** [comment]
Wow, okay great.  Give me a little bit and I'll do it.

Also, we are getting good signs from GNOME team.

**Comment by rich123** [comment]
That is good news on the Gnome front.  Hopefully they go the way of the last comment and stop reading the clipboard unless a paste is requested.  But whatever their outcome, the change will also help for other instances of the same behavior that are not nautilus (xclipboard, vnc, etc.).

**Comment by PorcelainMouse** [comment]
Wow, I'm impressed you worked up that patch so quickly.  I have tested it and it seems to resolved the conflict. I'm not sure what else to try, but I initiated a username copy with nautilus running and PWGorilla *did not* immediately copy the password to the clipboard, which was the symptom I reported.

**Comment by rich123** [comment]
Well, in my defense :) I've known of the issue for a long time (because of xclipboard/xcutsel).  But as almost no one beyond a few greybeards even know about xclipboard/xcutsel in today's world I didn't try to create a fix for a long time (because few were using anything that would trigger the issue, and those few who were could turn off xclipboard/xcutsel as needed.  So I've had a lot of time for thinking through a possible fix before ever writing anything.

Now that Nautilus seems to have added this "feature" for some reason, it was clear it was finally time to actually write the code for the algorithm I'd been thinking through (on and off) for a long time.  After having the algo. coalesce over such a time span, actually creating the code was, in the end, the easy part.

I'll go ahead and close this issue out now, as a fix is in place on pre160, even if it is not (yet) in the official 'package'.

**Comment by PorcelainMouse** [comment]
Yikes.  This problem is back.  Something changed and how even your workaround doesn't help.  I noticed this a while ago, but it seemed to be only sometimes.  When you closed it, it worked all the time, as best I can remember.  Then, a few months ago, if I copied the username, it would get read, causing the password to get copied.  But, if I tried again, immediately, it would *not* get copied.  Now, it's even worse after Fedora30.

**Comment by rich123** [comment]
Hmm, so instead of simply stopping messing around with the clipboard in a file manager, when the user has not performed a copy or paste, the gnome dev's go and make it worse?  Sad.

My first gut feeling is to try tweaking the "auto copy latency" value in the preferences.  The fact that you report it as intermittent likely means the current latency value needs to be just a little bit longer.

**Comment by PorcelainMouse** [comment]
Okay, I doubled the latency parameter.  I'll get back to you after a bit of testing.

**Comment by rich123** [comment]
The way this change works, that latency value determines how long PWGorilla waits after a paste before switching from sending the user ID to sending the password.  If additional 'false' pastes are generated during that time window, the Username is again provided as the paste value.

**Comment by rich123** [comment]
Of course, the best fix would be for the Gnome dev's to stop messing with the clipboard in a file manager unless the user explicitly has requested the file manager copy or paste something to/from the clipboard.  But due to the overall arrogance of the Gnome dev's I doubt that is likely to happen.
