### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by SavSanta** [zdia/gorilla#195]
I have pw-gorilla  1.5.3.7 installed from Linux Mint package manager.

So I was trying to run the pre-160 gorilla.tcl file. According to the readme it should run fine from a launch from the terminal. It does seem to launch when I run ./gorilla.tcl and the difference I can see is that the pre-160 has a version listed in the startmenu that says Password Gorilla 1.5.3.8.

 It also curiously enough does populate automatically with a path to a test database that I created in 1.5.3.7? 
However, everytime I attempt to open it crashes? Could this be due to the program reading the wrong config files from that installed on pw-gorilla from the package manager?

Here is a short snippet of the ending strace right after hitting enter after providing the password to the Database file

```
writev(5, [{"7\0\5\0Y\2 \4W\2 \4\4\0\0\0uuu\0F\0\5\0X\2 \4Y\2 \4"..., 408}, {NULL, 0}, {"", 0}], 3) = 408
poll([{fd=5, events=POLLIN}], 1, 4294967295) = 1 ([{fd=5, revents=POLLIN}])
recvmsg(5, {msg_name(0)=NULL, msg_iov(1)=[{"\1\2\343\v\0\0\0\0Z\0 \4\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(5, 0x7ffe79e916d0, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(5, 0x7ffe79e916d0, 0)           = -1 EAGAIN (Resource temporarily unavailable)
stat("/tmp/test.psafe3", {st_mode=S_IFREG|0644, st_size=600, ...}) = 0
lstat("/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=678, ...}) = 0
open("/tmp/test.psafe3", O_RDONLY)      = 6
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0
ioctl(6, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0x7ffe79e916f0) = -1 ENOTTY (Inappropriate ioctl for device)
read(6, "PWS3\276\364\221h\325\245ec\303\345\233\217\261bsBXN\3\316~\341\274i\r\266O\361"..., 4096) = 600
lseek(6, 0, SEEK_SET)                   = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0} ---
+++ killed by SIGSEGV +++
Segmentation fault

```

**Comment by rich123** [comment]
> It also curiously enough does populate automatically with a path to a test database that I created in 1.5.3.7?

This is normal.  The list of recent opened files is saved in the .gorillarc file in your home directory, so pre-160 was simply picking up the list of recent files last saved by 1.5.3.7.

> However, everytime I attempt to open it crashes? 

Not good.

> Could this be due to the program reading the wrong config files from that installed on pw-gorilla from the package manager?

This is easy to test.  Exit pre-160 (if it is running) and 1.5.3.7 (if it is running).  I.e., exit all instance that are running.  Then rename the .gorillarc in your homedir to some other name.  Then restart pre-160 from a terminal.  Then open the same temp file that causes the crash.  See if a crash occurs or not.

You indicate that this safe is a "test database".  By that do you mean it contains no sensitive info (i.e., it is just junk entries) and that the master password is also not your regular Gorilla password?

If yes, then given the point where the segmentation fault happens from the strace, this looks like that file might be corrupt.  If so, I'd be interested in having a copy (and knowing the password) [but **only** if it contains nothing of *any* value and the master password is just also a test password].

Also, does 1.5.3.7 open the file successfully?  If yes, then I'd *really* like a copy of the file, but only if it contains nothing of value, because I'd like to trace out why it crashes, and doing that tracing would be way faster if I had a copy of the bad file.

**Comment by SavSanta** [comment]
Greetings @rich123 

The temp file was created in Password Gorilla 1.5.3.7. It opens correctly and such in that version. It does contain junk data, but the creation of it was just to see some processes.

I've also uninstalled the package manager version of Password Gorilla. However, the segmentation fault occurs still. I've also renamed gorillarc file, and the segfault still occurs.

Ive tested a few different paths and the segmentation fault happens regardless if I try to open my current working psafes (either my throwaway test or the one i use for my actual passwords)  or if I try to create a new psafe in pre160.

I will try to upload a screencast.

**Comment by SavSanta** [comment]
Here it is.
[Example.zip](https://github.com/zdia/gorilla/files/2575794/Example.zip)

**Comment by rich123** [comment]
The test file opens for me without creating a segfault.

So the next test to try is to disable the compiled extensions.  If you want to narrow it down to a specific one, you'll want to disable them one at a time and test opening the file to see if it segfaults.

The first one to try is the sha256 code from tcllib.  It is located in these two locations relative to the "sources" directory of the source bundle: tcllib/sha256c/linux-ix86/ and tcllib/sha256c/linux-x86_64/.  Inside both directories are two *.so files.  One at a time, rename each to something other than *.so (*.so.off is good) and restart gorilla to see if the segfault occurs.  There are two directories because one is for 32-bit Linux systems (ix86) and the other is for 64-bit systems (x86_64).  You should only need to rename the single one (ix86 or x86_64) that matches your system.

The second one is the twofish extension.  It is located in twofish/linux-ix86/  and twofish/linux-x86_64/ relative to the "sources" directory.  Again pick the proper directory (32 vs. 64 bit) and rename the *.so inside to another name and try restarting Gorilla.

I suspect that one of these three is the culprit.  When you find one that fixes things, rename all the others back to *.so and see if renaming just that one fixes/creates the issue.  Then we know we have found the culprit.  The next steps will be indicated by which one is at fault.

**Comment by rich123** [comment]
Ok, then this one may be an easy fix.

In your terminal, change directory into the twofish directory below sources.

Next, presuming you have make and gcc installed on your  system, type 'make clean' (without the quotes) followed by 'make' (without the quotes).  This should build a new twofish.so file.

If you receive an error message about not being able to find a file libtclstub8.5 then edit the 'Makefile' and at about line 39 change '-ltclstub8.5' to '-ltclstub8.6' and try the two make commands above again.

One of these should create a new twofish.so file.  Move it into the linux-x86_64 directory in place of the old twofish.so file and try again.  I suspect that recompiling the twofish.so file will fix things.

**Comment by SavSanta** [comment]
Had to create a fake tcl.pc file as i was getting pkg-config errors.

After that it couldnt find tcl.h. So I had to edit the include line to #include <tcl8.6/tcl.h>

Then i ran the 'make' command without quotes. The output
```
~/gorilla-pre160/sources/twofish $ make
gcc -std=c99 -Wall -fPIC -O3 -fomit-frame-pointer   -DUSE_TCL_STUBS  -o twofish2tcl.o -c twofish2tcl.c
gcc -o twofish2tcl.so twofish2tcl.o -fPIC -shared   -ltclstub8.6
```

It appears to have generated **twofish2tcl.so** instead of your earlier mentioned **twofish.so**.

 Further I suppose really how do we test to make sure the twofish.so library is actually corrected, as we know simply removing the current one that ships with the GIT source allows you to progress past the segmentation fault.

**Comment by rich123** [comment]
> Had to create a fake tcl.pc file as i was getting pkg-config errors.

> After that it couldnt find tcl.h. So I had to edit the include line to #include <tcl8.6/tcl.h> on Ubuntu/Mint

You might also have needed to install the development pack for Tcl as well (as Ubuntu has always separated apps into an "application" package and a separate "development" package, and for any development work (compiling against the library) the "development" package needs to be installed.  I don't necessarily agree that this is a good idea on their part anymore, what with multi tera-byte drives being so cheap, but it is what it is in the Ubuntu world.

> It appears to have generated twofish2tcl.so instead of your earlier mentioned twofish.so

Ah, that indicates I need to tweak the makefile.  Just rename the newly generated .so file to the same name as was in the X86_64 dir (if you are on a 64-bit system) and place it in the dir where you renamed the old file.

> Further I suppose really how do we test to make sure the twofish.so library is actually corrected, 

We don't, yet, at least not until you try moving the new .so file into the location of the old .so file and attempting to open the test db.  If the test db opens, then the cause is likely what I've been suspecting, that your system has a newer glibc than the one the original .so file was compiled on, and the segfault was due to a difference in linkage between the two.

> as we know simply removing the current one that ships with the GIT source allows you to progress past the segmentation fault.

Well, you've gone one step further in that you've now created a new object file, with proper linkage to your glibc, from the C source for the twofish extension.  So if the segfault goes away (I suspect it will, as I did not get a segfault when I tried opening the test DB) then the cause was an outdated *.so as compared to your system.  If you still get a segfault, well, then in that case I'm going to have to spin up a VM, install the version of Mint you have, and do some digging.  But I'm expecting the recompile will likely fix things, which then means I need to also recompile the master *.so files here as well.

**Comment by SavSanta** [comment]
Ahh okay. Thanks for the explanation.

So I renamed the file to _twofish.so_ and placed it in _~/gorilla-pre160/sources/twofish/linux-x86_64_
Upon launch. I still received the segmentation fault. :cry: 

Im not sure what version of Mint to provide you with as this is a Mint that has been had since maybe 2011 and just been upgraded rolling style. Though currently the Ubuntu repos sources are 14.04 but it may be better to let me know if you need specific application versions

**Comment by SavSanta** [comment]
I've installed the pre160 on a Ubuntu Xenial box. Do you happen to have that Test DB I uploaded here earlier? Thank you.

**Comment by rich123** [comment]
[test.psafe3.zip](https://github.com/zdia/gorilla/files/2676140/test.psafe3.zip)

It should be uploaded on this reply now.

**Comment by SavSanta** [comment]
Hi Rich,

Thanks for the reply. Yes I did the same thing with a different version of Linux Mint in my vCloud/Vsphere. I cant recreate the segfault myself. I dont know. It's funny that you reply now. As I was just getting ready to close this out as it's too tricky. Thanks however for the update
