### ISSUE TITLE
-- Question - is this project is active?

### ISSUE THREAD

**Issue by surapuramakhil** [zdia/gorilla#204]
the reason why I am asking this I see a lot of issues which are a year ago old. 
and the worst one is 9 years ago. I am also seeing about the pull request which is left alone.

I love password gorilla for it generate password capability and remembering of the password. thanks for it.

**Comment by rich123** [comment]
> is this project is active?

That depends upon how you define "active".  The last code change was pushed into the pre160 branch on May 19, 2019, so that seems somewhat "active" (esp. considering that PWGorilla is a side project and my available time for devotion to side projects has been small in quantity for quite some time).

> I see a lot of issues which are a year ago old. and the worst one is 9 years ago

Did you just look at the titles and dates on the summary, or did you look inside any of the issues?  The 9 year old one was fixed in commit 7c07065.  Yes, the issue is technically open, but I've been lax about worrying about closing them, so they've accumulated.

> the pull request which is left alone.

Did you look inside again?  One of them had already been fixed on the pre160 branch when the pull request came in.  Plus, unless github's fixed things, their pull request web interface is awful.  One can't redirect a pull request onto a different branch from the web interface, the options are "apply" or "don't apply", and so most often I hand apply the pull requests (so they go on the branch I want them on) but of course this does not close out the web interface automatically.  And then I often overlook going back and manually closing out the request.

So, still around, but progress is very slow.  I do want to try to roll up a 1.6.0 bundle at some point, so if you want you could give the beta2 bundle a test (see https://gorilla.dp100.com/downloads/) and report if you find any issues.

**Comment by surapuramakhil** [comment]
@rich123 thank you. for reverting with the reply.

Sure I will do that in my free time and report issues. if I find any:+1: .
