### ISSUE TITLE
Password Gorilla occasionally adds garbage

### ISSUE THREAD

**Issue by stanley3384** [zdia/gorilla#212]
It works great and I like it, only issue is it creating a couple of new groups with a garbage name with one equally garbage logins in each of them.  I just select the garbage groups and delete them.  It is fine other than that.  
![Gorilla](https://user-images.githubusercontent.com/25163951/84609422-ef2f6c00-ae84-11ea-9306-b18236a12f95.png)
Please see attached.  Best regards Ian.

**Comment by stanley3384** [comment]
Yes I should have said version 1.5.3.7 on LinuxMint 18.3 and I pulled it from the Mint repository.

**Comment by rich123** [comment]
I suspect that your issue may be related to these prior issues: #193, #206, and/or #196.

Since you are on 1.5.3.7, I'd recommend you give the pre1.6.0 branch a try.  Issue #182 shows some instructions on how to upgrade for Ubuntu.  I don't know how much those apply for Mint, but they give you a beginning to follow.  I suspect this issue has been fixed by one or more of those three issues listed at the start here.

**Comment by stanley3384** [comment]
Thanks rich123, that was simpler than running configure, make etc.  I now have Vsn 160 Beta 2 and only have to switch the click in Accessories, it also told me that " 1 UUID was fixed and needed to be saved".  I'll let you know if it gets messed up again.  Many thanks Ian.
