### ISSUE TITLE
Would a "export" to BASE64 be viable?

### ISSUE THREAD

**Issue by SavSanta** [zdia/gorilla#216]
Something I have been thinking about is adding an additional method to export the psafe3 password database to BASE64. Only because I backup a copy of my password database on my private pastebin. Usually because pastebin only supports textual characters I have to manually convert he psafe3 binary file into base64.

Wondering if that would be an interested feature to implement?

**Comment by rich123** [comment]
The library routines are present to do so.  Tcl 8.6 includes base64 encode/decode as part of the [binary] command.  Tcllib includes a base64 module for use with Tcl before 8.6.  Right now Gorilla is still compatible with 8.5, and it might be worthwhile maintaining that compatibility for a while longer.

With that said, this also feels a bit like a rather one-off niche feature.  So far I do not believe I've ever encountered a reason myself to need to textually encode any of my password files.  So my limited perspective in that regards is that it seems the feature might not get a lot of usage.

I can also see why you'd like the feature, it saves you the step of manually running 'base64' or some other encoder on the password file before storing a copy into pastebin.  To be honest, I never considered the possibility of using pastebin as a "backup utility" in this manner.

One more question, does pastebin (at least for the private version) provide any API and/or can you insert a "paste" via curl/wget?  If it offers either option, you might be better served by writing a small bit of code that encodes to text and "pastes" the result into pastebin automatically.  Then you could use cron (or some other scheduling deamon) to do an automatic backup for you instead of performing it manually (which is how it sounds like you may be backing up now).  I know myself that before I finally setup a fully automatic cron driven backup system that I was lax at remembering to regularly backup, so having it be automatic when I finally set it up, was wonderful.

You might consider targeting your efforts in the direction of creating a "backup to pastebin" utility that can be automated, which would have broader usefulness than just backing up PWGorilla files.  And if you do, you might consider looking at the ascii85 encoder in Tcllib.  It will produce smaller 'textual' encoded output than base64, allowing larger files to be stored in pastebin.  The negative of ascii85 is there are fewer decoders readily available (besides the Tcllib decoder that is).

**Comment by SavSanta** [comment]
Rich123 alot of what you wrote is understandable and sensible. Thanks for the insight. Indeed that Pastebin private version does provide an API to upload pastes. It may make more sense to opt for the encoding to be done as part of a regular cronjob. I guess I was a bit overzealous in wanting to do something else with TCL. That's a better idea though. Cheers :D

**Comment by rich123** [comment]
It is quite feasible you could build the "generic pastebin auto-backup tool" with Tcl if you want to gain some more Tcl experience.  The http module will provide the basics necessary for submitting the encoded data to the pastebin API.  You may have to create some of the specifics on top of the http module, but this "cronjob executable automatic pastebin backup tool" I suggested could be built with Tcl.

Curl or wget would be useful for determining the right way to call the API, with what parameters, and method.  Then it should just be creating the necessary code to use the http module to make the call.

**Comment by rich123** [comment]
It is quite feasible you could build the "generic pastebin auto-backup tool" with Tcl if you want to gain some more Tcl experience.  The http module will provide the basics necessary for submitting the encoded data to the pastebin API.  You may have to create some of the specifics on top of the http module, but this "cronjob executable automatic pastebin backup tool" I suggested could be built with Tcl.

Curl or wget would be useful for determining the right way to call the API, with what parameters, and method.  Then it should just be creating the necessary code to use the http module to make the call.

**Comment by rich123** [comment]
It is quite feasible you could build the "generic pastebin auto-backup tool" with Tcl if you want to gain some more Tcl experience.  The http module will provide the basics necessary for submitting the encoded data to the pastebin API.  You may have to create some of the specifics on top of the http module, but this "cronjob executable automatic pastebin backup tool" I suggested could be built with Tcl.

Curl or wget would be useful for determining the right way to call the API, with what parameters, and method.  Then it should just be creating the necessary code to use the http module to make the call.

**Comment by SavSanta** [comment]
Closing this out as that makes sense imo.
